# Generated by Django 3.1.7 on 2024-02-17 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_better_passwords', '0003_auto_20240217_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecord',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='password_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
