# Generated by Django 3.1.7 on 2024-02-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_better_passwords', '0004_auto_20240217_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecord',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
