# Generated by Django 3.1.7 on 2024-02-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_better_passwords', '0005_auto_20240217_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecord',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
